services:
  - type: web
    name: whatsapp-platform-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Add your environment variables in Render Dashboard:
      # - SUPABASE_URL
      # - SUPABASE_ANON_KEY
      # - SUPABASE_SERVICE_ROLE_KEY
      # - JWT_SECRET
      # - GOOGLE_CLIENT_ID
      # - GOOGLE_CLIENT_SECRET
      # - FRONTEND_URL
      # - ADMIN_URL (optional)
      # - BACKEND_URL (optional, defaults to service URL)

