const crypto = require('crypto');

/**
 * Generate a secure API key
 * Format: wp_live_[64 hex characters]
 * Example: wp_live_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2
 * 
 * IMPORTANT: API keys generated by this function NEVER expire.
 * They remain valid indefinitely until explicitly revoked by the user.
 * Only the user can revoke their API key via DELETE /api/api-keys/current
 */
function generateApiKey() {
  const randomBytes = crypto.randomBytes(32);
  const hexString = randomBytes.toString('hex');
  return `wp_live_${hexString}`;
}

/**
 * Validate API key format
 */
function validateApiKeyFormat(apiKey) {
  if (!apiKey || typeof apiKey !== 'string') {
    return false;
  }
  
  // Check format: wp_live_[64 hex characters]
  const regex = /^wp_live_[a-f0-9]{64}$/;
  return regex.test(apiKey);
}

module.exports = {
  generateApiKey,
  validateApiKeyFormat
};

